# Generated by Django 4.1.7 on 2023-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
