# Generated by Django 4.1.7 on 2023-04-04 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 3, 20, 47, 18, 555743)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(default="Nan", max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(default="Nan", max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
