# Generated by Django 4.1.7 on 2023-04-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0005_alter_behaviors_behavior_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behaviors",
            name="behavior",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="behaviorstrategies",
            name="behavior_strategy",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="consequences",
            name="consequence",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="consequencestrategies",
            name="consequence_strategy",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="locations",
            name="location",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="settings",
            name="setting",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="settingstrategies",
            name="setting_strategy",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="strengths",
            name="strength",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="triggers",
            name="trigger",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="triggerstrategies",
            name="trigger_strategy",
            field=models.CharField(max_length=150),
        ),
    ]
