# Generated by Django 4.1.7 on 2023-04-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0008_teacher_email_verified_alter_teacher_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behaviors",
            name="behavior",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="behaviorstrategies",
            name="behavior_strategy",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="consequences",
            name="consequence",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="consequencestrategies",
            name="consequence_strategy",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="locations",
            name="location",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="setting",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="settingstrategies",
            name="setting_strategy",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="strengths",
            name="strength",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="triggers",
            name="trigger",
            field=models.TextField(blank="", default="", null=True),
        ),
        migrations.AlterField(
            model_name="triggerstrategies",
            name="trigger_strategy",
            field=models.TextField(blank="", default="", null=True),
        ),
    ]
