# Generated by Django 4.1.7 on 2023-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_alter_behaviors_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerstrategies',
            name='question_number',
            field=models.CharField(blank='', default='', max_length=20),
        ),
    ]
