# Generated by Django 4.1.7 on 2023-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_triggerstrategies_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorstrategies',
            name='question_number',
            field=models.CharField(blank='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consequencestrategies',
            name='question_number',
            field=models.CharField(blank='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='settingstrategies',
            name='question_number',
            field=models.CharField(blank='', default='', max_length=20),
        ),
    ]
