# Generated by Django 4.1.7 on 2023-04-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0011_behaviorstrategies_question_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Custom_Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("strength", "strength"),
                            ("locations", "locations"),
                            ("setting", "setting"),
                            ("trigger", "trigger"),
                            ("behavior", "behavior"),
                            ("consequence", "consequence"),
                            ("setting_strategy", "setting_strategy"),
                            ("trigger_strategy", "trigger_strategy"),
                            ("behavior_strategy", "behavior_strategy"),
                            ("consequence_strategy", "consequence_strategy"),
                        ],
                        default="strength",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("text", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="is_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="answer",
            name="other_type",
            field=models.CharField(
                choices=[
                    ("strength", "strength"),
                    ("locations", "locations"),
                    ("setting", "setting"),
                    ("trigger", "trigger"),
                    ("behavior", "behavior"),
                    ("consequence", "consequence"),
                    ("setting_strategy", "setting_strategy"),
                    ("trigger_strategy", "trigger_strategy"),
                    ("behavior_strategy", "behavior_strategy"),
                    ("consequence_strategy", "consequence_strategy"),
                ],
                default="strength",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="behavior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.behaviors",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="behavior_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.behaviorstrategies",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="consequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.consequences",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="consequence_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.consequencestrategies",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="locations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.locations",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="setting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.settings",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="setting_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.settingstrategies",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="strength",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.strengths",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.triggers",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="trigger_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.triggerstrategies",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="other_answer",
            field=models.ManyToManyField(to="questionnaire.custom_strategy"),
        ),
    ]
