# Generated by Django 4.1.7 on 2023-05-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "questionnaire",
            "0012_custom_strategy_answer_is_other_answer_other_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consequences",
            options={
                "verbose_name": "Maintaining Consequence",
                "verbose_name_plural": "Maintaining Consequences",
            },
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={
                "verbose_name": "Setting Event",
                "verbose_name_plural": "Setting Events",
            },
        ),
        migrations.AlterModelOptions(
            name="settingstrategies",
            options={
                "verbose_name": "Setting Event Strategies",
                "verbose_name_plural": "Setting Events Strategies",
            },
        ),
        migrations.AlterModelOptions(
            name="triggers",
            options={
                "verbose_name": "Triggering Antecedent",
                "verbose_name_plural": "Triggering Antecedents",
            },
        ),
        migrations.AlterModelOptions(
            name="triggerstrategies",
            options={
                "verbose_name": "Antecedent strategy",
                "verbose_name_plural": "Antecedent strategies",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="custom_answer",
        ),
        migrations.RemoveField(
            model_name="settingstrategies",
            name="question_number",
        ),
        migrations.AlterField(
            model_name="answer",
            name="consequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.consequences",
                verbose_name="Maintaining Consequence",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="setting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.settings",
                verbose_name="Setting Event",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="setting_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.settingstrategies",
                verbose_name="Setting Event Strategy",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.triggers",
                verbose_name="Triggering Antecedent",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="trigger_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.triggerstrategies",
                verbose_name="Antecedent Strategy",
            ),
        ),
    ]
